DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS employeeRole;
DROP TABLE IF EXISTS employee;

CREATE TABLE department (
dept_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
dept_name VARCHAR(30) NOT NULL
);

CREATE TABLE role (
role_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30),
salary DECIMAL,
dept_id INTEGER,
CONSTRAINT fk_department_id 
FOREIGN KEY (dept_id)
REFERENCES department(dept_id) ON DELETE SET NULL
);

CREATE TABLE employee (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER,
manager_id INTEGER UNIQUE,
CONSTRAINT fk_role_id
FOREIGN KEY (role_id)
REFERENCES role(role_id) ON DELETE SET NULL,
INDEX id_manager(manager_id),
CONSTRAINT fk_manager_id
FOREIGN KEY (manager_id)
REFERENCES employee(manager_id) ON DELETE SET NULL
);